interface Coin {
  count: number;
  timestamp: string;
  symbols: {
    binance_symbol: string[];
    okex_symbol: string[];
  };
} 

const binance_okex_common_symbols: Coin = {
  "count": 260,
  "timestamp": "2025-12-19T11:26:14.325Z",
  "symbols": {
    "binance_symbol": [
      // "BTCUSDT",
      // "ETHUSDT",
      // "BNBUSDT",
      // "NEOUSDT",
      // "LTCUSDT",
      // "QTUMUSDT",
      // "ADAUSDT",
      // "XRPUSDT",
      // "IOTAUSDT",
      // "XLMUSDT",
      // "ONTUSDT",
      // "TRXUSDT",
      // "ETCUSDT",
      // "ICXUSDT",
      // "VETUSDT",
      // "LINKUSDT",
      // "ONGUSDT",
      // "ZILUSDT",
      // "ZRXUSDT",
      // "FETUSDT",
      // "BATUSDT",
      // "ZECUSDT",
      // "IOSTUSDT",
      // "CELRUSDT",
      // "DASHUSDT",
      // "THETAUSDT",
      // "ENJUSDT",
      // "ATOMUSDT",
      // "TFUELUSDT",
      // "ONEUSDT",
      // "ALGOUSDT",
      // "DOGEUSDT",
      // "DUSKUSDT",
      // "ANKRUSDT",
      // "WINUSDT",
      // "COSUSDT",
      // "MTLUSDT",
      // "DENTUSDT",
      // "WANUSDT",
      // "FUNUSDT",
      // "CVCUSDT",
      // "CHZUSDT",
      // "BANDUSDT",
      // "XTZUSDT",
      // "NKNUSDT",
      // "STXUSDT",
      // "KAVAUSDT",
      // "ARPAUSDT",
      // "IOTXUSDT",
      // "RLCUSDT",
      // "BCHUSDT",
      // "FTTUSDT",
      // "OGNUSDT",
      // "BNTUSDT",
      // "MBLUSDT",
      // "COTIUSDT",
      // "DATAUSDT",
      // "SOLUSDT",
      // "CTSIUSDT",
      // "HIVEUSDT",
      // "CHRUSDT",
      // "ARDRUSDT",
      // "MDTUSDT",
      // "KNCUSDT",
      // "COMPUSDT",
      // "SCUSDT",
      // "ZENUSDT",
      // "SNXUSDT",
      // "VTHOUSDT",
      // "SXPUSDT",
      // "DCRUSDT",
      // "STORJUSDT",
      // "MANAUSDT",
      // "YFIUSDT",
      // "JSTUSDT",
      // "CRVUSDT",
      // "SANDUSDT",
      // "NMRUSDT",
      // "DOTUSDT",
      // "LUNAUSDT",
      // "RSRUSDT",
      // "PAXGUSDT",
      // "TRBUSDT",
      // "SUSHIUSDT",
      // "EGLDUSDT",
      // "DIAUSDT",
      // "FIOUSDT",
      // "UMAUSDT",
      // "BELUSDT",
      // "UNIUSDT",
      // "OXTUSDT",
      // "AVAXUSDT",
      // "UTKUSDT",
      // "AAVEUSDT",
      // "NEARUSDT",
      // "FILUSDT",
      // "INJUSDT",
      // "AXSUSDT",
      // "STRAXUSDT",
      // "ROSEUSDT",
      // "AVAUSDT",
      // "JUVUSDT",
      // "PSGUSDT",
      // "1INCHUSDT",
      // "OGUSDT",
      // "ATMUSDT",
      // "ASRUSDT",
      // "CELOUSDT",
      // "RIFUSDT",
      // "TRUUSDT",
      // "TWTUSDT",
      // "SFPUSDT",
      "DODOUSDT",
      "CAKEUSDT",
      "PONDUSDT",
      "DEGOUSDT",
      "ALICEUSDT",
      "CFXUSDT",
      "PUNDIXUSDT",
      "TLMUSDT",
      "BARUSDT",
      "FORTHUSDT",
      "SLPUSDT",
      "SHIBUSDT",
      "ICPUSDT",
      "LPTUSDT",
      "XVGUSDT",
      "ATAUSDT",
      "GTCUSDT",
      "PHAUSDT",
      "MLNUSDT",
      "DEXEUSDT",
      "C98USDT",
      "QNTUSDT",
      "FLOWUSDT",
      "MINAUSDT",
      "RAYUSDT",
      "FARMUSDT",
      "QUICKUSDT",
      "MBOXUSDT",
      "REQUSDT",
      "GHSTUSDT",
      "WAXPUSDT",
      "GNOUSDT",
      "XECUSDT",
      "DYDXUSDT",
      "IDEXUSDT",
      "GALAUSDT",
      "YGGUSDT",
      "SYSUSDT",
      "FIDAUSDT",
      "AGLDUSDT",
      "RADUSDT",
      "RAREUSDT",
      "LAZIOUSDT",
      "CHESSUSDT",
      "ADXUSDT",
      "AUCTIONUSDT",
      "MOVRUSDT",
      "CITYUSDT",
      "ENSUSDT",
      "QIUSDT",
      "PORTOUSDT",
      "POWRUSDT",
      "JASMYUSDT",
      "AMPUSDT",
      "ALCXUSDT",
      "SANTOSUSDT",
      "BICOUSDT",
      "FXSUSDT",
      "HIGHUSDT",
      "CVXUSDT",
      "SPELLUSDT",
      "ACHUSDT",
      "IMXUSDT",
      "SCRTUSDT",
      "API3USDT",
      "ACAUSDT",
      "WOOUSDT",
      "ALPINEUSDT",
      "TUSDT",
      "GMTUSDT",
      "APEUSDT",
      "STEEMUSDT",
      "NEXOUSDT",
      "LDOUSDT",
      "OPUSDT",
      "LUNCUSDT",
      "APTUSDT",
      "HFTUSDT",
      "PHBUSDT",
      "HOOKUSDT",
      "RPLUSDT",
      "GNSUSDT",
      "SSVUSDT",
      "GLMUSDT",
      "QKCUSDT",
      "ARBUSDT",
      "WBTCUSDT",
      "EDUUSDT",
      "SUIUSDT",
      "PEPEUSDT",
      "FLOKIUSDT",
      "ARKMUSDT",
      "SEIUSDT",
      "CYBERUSDT",
      "NTRNUSDT",
      "VICUSDT",
      "VANRYUSDT",
      "JTOUSDT",
      "BONKUSDT",
      "ACEUSDT",
      "NFPUSDT",
      "AIUSDT",
      "MANTAUSDT",
      "ALTUSDT",
      "DYMUSDT",
      "PIXELUSDT",
      "STRKUSDT",
      "PORTALUSDT",
      "AEVOUSDT",
      "ETHFIUSDT",
      "WUSDT",
      "TNSRUSDT",
      "SAGAUSDT",
      "BBUSDT",
      "NOTUSDT",
      "ZROUSDT",
      "GUSDT",
      "BANANAUSDT",
      "TONUSDT",
      "POLUSDT",
      "EIGENUSDT",
      "LUMIAUSDT",
      "MOVEUSDT",
      "MEUSDT",
      "PENGUUSDT",
      "DUSDT",
      "COOKIEUSDT",
      "SUSDT",
      "TRUMPUSDT",
      "TSTUSDT",
      "HEIUSDT",
      "REDUSDT",
      "EPICUSDT",
      "FORMUSDT",
      "PARTIUSDT",
      "MUBARAKUSDT",
      "BANANAS31USDT",
      "VIRTUALUSDT",
      "SIGNUSDT",
      "NXPCUSDT",
      "AWEUSDT",
      "HUMAUSDT",
      "AUSDT",
      "SOPHUSDT",
      "RESOLVUSDT",
      "LAUSDT",
      "CUSDT",
      "ASTERUSDT"
    ],
    "okex_symbol": [
      // "BTC-USDT",
      // "ETH-USDT",
      // "BNB-USDT",
      // "NEO-USDT",
      // "LTC-USDT",
      // "QTUM-USDT",
      // "ADA-USDT",
      // "XRP-USDT",
      // "IOTA-USDT",
      // "XLM-USDT",
      // "ONT-USDT",
      // "TRX-USDT",
      // "ETC-USDT",
      // "ICX-USDT",
      // "VET-USDT",
      // "LINK-USDT",
      // "ONG-USDT",
      // "ZIL-USDT",
      // "ZRX-USDT",
      // "FET-USDT",
      // "BAT-USDT",
      // "ZEC-USDT",
      // "IOST-USDT",
      // "CELR-USDT",
      // "DASH-USDT",
      // "THETA-USDT",
      // "ENJ-USDT",
      // "ATOM-USDT",
      // "TFUEL-USDT",
      // "ONE-USDT",
      // "ALGO-USDT",
      // "DOGE-USDT",
      // "DUSK-USDT",
      // "ANKR-USDT",
      // "WIN-USDT",
      // "COS-USDT",
      // "MTL-USDT",
      // "DENT-USDT",
      // "WAN-USDT",
      // "FUN-USDT",
      // "CVC-USDT",
      // "CHZ-USDT",
      // "BAND-USDT",
      // "XTZ-USDT",
      // "NKN-USDT",
      // "STX-USDT",
      // "KAVA-USDT",
      // "ARPA-USDT",
      // "IOTX-USDT",
      // "RLC-USDT",
      // "BCH-USDT",
      // "FTT-USDT",
      // "OGN-USDT",
      // "BNT-USDT",
      // "MBL-USDT",
      // "COTI-USDT",
      // "DATA-USDT",
      // "SOL-USDT",
      // "CTSI-USDT",
      // "HIVE-USDT",
      // "CHR-USDT",
      // "ARDR-USDT",
      // "MDT-USDT",
      // "KNC-USDT",
      // "COMP-USDT",
      // "SC-USDT",
      // "ZEN-USDT",
      // "SNX-USDT",
      // "VTHO-USDT",
      // "SXP-USDT",
      // "DCR-USDT",
      // "STORJ-USDT",
      // "MANA-USDT",
      // "YFI-USDT",
      // "JST-USDT",
      // "CRV-USDT",
      // "SAND-USDT",
      // "NMR-USDT",
      // "DOT-USDT",
      // "LUNA-USDT",
      // "RSR-USDT",
      // "PAXG-USDT",
      // "TRB-USDT",
      // "SUSHI-USDT",
      // "EGLD-USDT",
      // "DIA-USDT",
      // "FIO-USDT",
      // "UMA-USDT",
      // "BEL-USDT",
      // "UNI-USDT",
      // "OXT-USDT",
      // "AVAX-USDT",
      // "UTK-USDT",
      // "AAVE-USDT",
      // "NEAR-USDT",
      // "FIL-USDT",
      // "INJ-USDT",
      // "AXS-USDT",
      // "STRAX-USDT",
      // "ROSE-USDT",
      // "AVA-USDT",
      // "JUV-USDT",
      // "PSG-USDT",
      // "1INCH-USDT",
      // "OG-USDT",
      // "ATM-USDT",
      // "ASR-USDT",
      // "CELO-USDT",
      // "RIF-USDT",
      // "TRU-USDT",
      // "TWT-USDT",
      // "SFP-USDT",
      "DODO-USDT",
      "CAKE-USDT",
      "POND-USDT",
      "DEGO-USDT",
      "ALICE-USDT",
      "CFX-USDT",
      "PUNDIX-USDT",
      "TLM-USDT",
      "BAR-USDT",
      "FORTH-USDT",
      "SLP-USDT",
      "SHIB-USDT",
      "ICP-USDT",
      "LPT-USDT",
      "XVG-USDT",
      "ATA-USDT",
      "GTC-USDT",
      "PHA-USDT",
      "MLN-USDT",
      "DEXE-USDT",
      "C98-USDT",
      "QNT-USDT",
      "FLOW-USDT",
      "MINA-USDT",
      "RAY-USDT",
      "FARM-USDT",
      "QUICK-USDT",
      "MBOX-USDT",
      "REQ-USDT",
      "GHST-USDT",
      "WAXP-USDT",
      "GNO-USDT",
      "XEC-USDT",
      "DYDX-USDT",
      "IDEX-USDT",
      "GALA-USDT",
      "YGG-USDT",
      "SYS-USDT",
      "FIDA-USDT",
      "AGLD-USDT",
      "RAD-USDT",
      "RARE-USDT",
      "LAZIO-USDT",
      "CHESS-USDT",
      "ADX-USDT",
      "AUCTION-USDT",
      "MOVR-USDT",
      "CITY-USDT",
      "ENS-USDT",
      "QI-USDT",
      "PORTO-USDT",
      "POWR-USDT",
      "JASMY-USDT",
      "AMP-USDT",
      "ALCX-USDT",
      "SANTOS-USDT",
      "BICO-USDT",
      "FXS-USDT",
      "HIGH-USDT",
      "CVX-USDT",
      "SPELL-USDT",
      "ACH-USDT",
      "IMX-USDT",
      "SCRT-USDT",
      "API3-USDT",
      "ACA-USDT",
      "WOO-USDT",
      "ALPINE-USDT",
      "T-USDT",
      "GMT-USDT",
      "APE-USDT",
      "STEEM-USDT",
      "NEXO-USDT",
      "LDO-USDT",
      "OP-USDT",
      "LUNC-USDT",
      "APT-USDT",
      "HFT-USDT",
      "PHB-USDT",
      "HOOK-USDT",
      "RPL-USDT",
      "GNS-USDT",
      "SSV-USDT",
      "GLM-USDT",
      "QKC-USDT",
      "ARB-USDT",
      "WBTC-USDT",
      "EDU-USDT",
      "SUI-USDT",
      "PEPE-USDT",
      "FLOKI-USDT",
      "ARKM-USDT",
      "SEI-USDT",
      "CYBER-USDT",
      "NTRN-USDT",
      "VIC-USDT",
      "VANRY-USDT",
      "JTO-USDT",
      "BONK-USDT",
      "ACE-USDT",
      "NFP-USDT",
      "AI-USDT",
      "MANTA-USDT",
      "ALT-USDT",
      "DYM-USDT",
      "PIXEL-USDT",
      "STRK-USDT",
      "PORTAL-USDT",
      "AEVO-USDT",
      "ETHFI-USDT",
      "W-USDT",
      "TNSR-USDT",
      "SAGA-USDT",
      "BB-USDT",
      "NOT-USDT",
      "ZRO-USDT",
      "G-USDT",
      "BANANA-USDT",
      "TON-USDT",
      "POL-USDT",
      "EIGEN-USDT",
      "LUMIA-USDT",
      "MOVE-USDT",
      "ME-USDT",
      "PENGU-USDT",
      "D-USDT",
      "COOKIE-USDT",
      "S-USDT",
      "TRUMP-USDT",
      "TST-USDT",
      "HEI-USDT",
      "RED-USDT",
      "EPIC-USDT",
      "FORM-USDT",
      "PARTI-USDT",
      "MUBARAK-USDT",
      "BANANAS31-USDT",
      "VIRTUAL-USDT",
      "SIGN-USDT",
      "NXPC-USDT",
      "AWE-USDT",
      "HUMA-USDT",
      "A-USDT",
      "SOPH-USDT",
      "RESOLV-USDT",
      "LA-USDT",
      "C-USDT",
      "ASTER-USDT"
    ]
  }
} 

export default binance_okex_common_symbols;